# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  impermanence.persistentFs = {
    device = "/dev/disk/by-uuid/4469e0ce-667e-4770-b6bd-87bd86bf064f";
    fsType = "btrfs";
    neededForBoot = true;
    options = [
      "compress=zstd"
      "relatime"
      "subvol=persistent"
    ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/4469e0ce-667e-4770-b6bd-87bd86bf064f";
    fsType = "btrfs";
    options = [
      "noatime"
      "subvol=swap"
    ];
  };

  fileSystems."/mnt/hdd" = {
    device = "/dev/disk/by-uuid/af274675-d182-433a-9d3a-3847fca77032";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "noatime"
    ];
  };
  fileSystems."/mnt/nvme" = {
    device = "/dev/disk/by-uuid/d30bcfd3-f6b0-4dae-970f-dea11890ab49";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/4469e0ce-667e-4770-b6bd-87bd86bf064f";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "relatime"
      "subvol=nix"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6CAC-F23D";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    {
      device = "/swap/swapfile";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
